name: CanvasKits
main: com.jcdesimp.canvaskits.CanvasKits
version: 0.1
author: Jcdesimp
authors: []
website:

softdepend: [Vault]

commands:
   canvaskits:
      aliases: [kits, kit]
      description: The base Landlord command.
      usage: /<command> [command]
      permission: landlord.use
      permission-message: You don't have permission.